version: "3.9"

services:

  real-data-db:
    image: postgres
    environment:
      POSTGRES_DB: "real_data_db"
      POSTGRES_USER: "real_data_admin_user"
      POSTGRES_PASSWORD: "1111"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - .\db_data:/var/lib/postgresql/data
      - .\sql\01_init_tables.sql:/docker-entrypoint-initdb.d/01_init_tables.sql
    ports:
      - "5432:5432"
    networks:
      - backend
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

networks:
  backend:
